vich_uploader:
    db_driver: orm
    metadata: 
        type: attribute

    mappings:
       company_images:
           uri_prefix: /images/company
           upload_destination: '%kernel.project_dir%/public/images/company'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
